INSERT INTO cities_table(city) VALUES ('Skopje');
INSERT INTO cities_table(city) VALUES ('Tetovo');
INSERT INTO cities_table(city) VALUES ('Bitola');
INSERT INTO cities_table(city) VALUES ('Kumanovo');
INSERT INTO cities_table(city) VALUES ('Prilep');
INSERT INTO cities_table(city) VALUES ('Ohrid');
INSERT INTO cities_table(city) VALUES ('Veles');
INSERT INTO cities_table(city) VALUES ('Štip');
INSERT INTO cities_table(city) VALUES ('Gostivar');
INSERT INTO cities_table(city) VALUES ('Kočani');
INSERT INTO cities_table(city) VALUES ('Dračevo');
INSERT INTO cities_table(city) VALUES ('Struga');
INSERT INTO cities_table(city) VALUES ('Debar');
INSERT INTO cities_table(city) VALUES ('Strumica');
INSERT INTO cities_table(city) VALUES ('Vinica');
INSERT INTO cities_table(city) VALUES ('Probištip');
INSERT INTO cities_table(city) VALUES ('Aračinovo');
INSERT INTO cities_table(city) VALUES ('Kičevo');
INSERT INTO cities_table(city) VALUES ('Kavadarci');
INSERT INTO cities_table(city) VALUES ('Gevgelija');
INSERT INTO cities_table(city) VALUES ('Vrapčište');
INSERT INTO cities_table(city) VALUES ('Radoviš');
INSERT INTO cities_table(city) VALUES ('Berovo');
INSERT INTO cities_table(city) VALUES ('Kruševo');
INSERT INTO cities_table(city) VALUES ('Sveti Nikole');
INSERT INTO cities_table(city) VALUES ('Demir Kapija');
INSERT INTO cities_table(city) VALUES ('Kučevište');
INSERT INTO cities_table(city) VALUES ('Delčevo');
INSERT INTO cities_table(city) VALUES ('Bogdanci');
INSERT INTO cities_table(city) VALUES ('Rašče');
INSERT INTO cities_table(city) VALUES ('Negotino');
INSERT INTO cities_table(city) VALUES ('Vevčani');
INSERT INTO cities_table(city) VALUES ('Debrešte');
INSERT INTO cities_table(city) VALUES ('Labuništa');
INSERT INTO cities_table(city) VALUES ('Gradsko');
INSERT INTO cities_table(city) VALUES ('Valandovo');
INSERT INTO cities_table(city) VALUES ('Kriva Palanka');
INSERT INTO cities_table(city) VALUES ('Kratovo');
INSERT INTO cities_table(city) VALUES ('Krivogaštani');
INSERT INTO cities_table(city) VALUES ('Zrnovci');
INSERT INTO cities_table(city) VALUES ('Pehčevo');
INSERT INTO cities_table(city) VALUES ('Plasnica');
INSERT INTO cities_table(city) VALUES ('Mogila');
INSERT INTO cities_table(city) VALUES ('Tearce');
INSERT INTO cities_table(city) VALUES ('Novaci');
INSERT INTO cities_table(city) VALUES ('Rosoman');
INSERT INTO cities_table(city) VALUES ('Novo Selo');
INSERT INTO cities_table(city) VALUES ('Bosilovo');
INSERT INTO cities_table(city) VALUES ('Konče');
INSERT INTO cities_table(city) VALUES ('Rostuša');
INSERT INTO cities_table(city) VALUES ('Jegunovce');
INSERT INTO cities_table(city) VALUES ('Rankovce');
INSERT INTO cities_table(city) VALUES ('Sopište');
INSERT INTO cities_table(city) VALUES ('Obleševo');
INSERT INTO cities_table(city) VALUES ('Karbinci');
INSERT INTO cities_table(city) VALUES ('Vasilevo');
INSERT INTO cities_table(city) VALUES ('Petrovec');
INSERT INTO cities_table(city) VALUES ('Makedonski Brod');
INSERT INTO cities_table(city) VALUES ('Staro Nagoričane');
INSERT INTO relations_table(relation_from_id, relation_to_id, price, estimated_travel_time) VALUES (1, 4, 170, '45min');
INSERT INTO relations_table(relation_from_id, relation_to_id, price, estimated_travel_time) VALUES (4, 1, 170, '45min');
INSERT INTO relations_table(relation_from_id, relation_to_id, price, estimated_travel_time) VALUES (1, 2, 200, '1h');
INSERT INTO relations_table(relation_from_id, relation_to_id, price, estimated_travel_time) VALUES (2, 1, 200, '1h');
INSERT INTO relations_table(relation_from_id, relation_to_id, price, estimated_travel_time) VALUES (1, 3, 350, '3h');
INSERT INTO relations_table(relation_from_id, relation_to_id, price, estimated_travel_time) VALUES (3, 1, 350, '3h');
